### ISSUE TITLE
Gateway Roadmap

### ISSUE THREAD

**Issue by SparklingFun** [SparklingFun/cf-worker-gateway#4]
Next patch version:

- [x] allow & deny IP
- [x] IP jail (when request too many)
- [x] all features classify (not only deperacted)

Next minor version:

- <del>improve gateway effect</del>

**Comment by SparklingFun** [comment]
### Q: Why not take optimization as the first priority task?

A: Because optimize too much will cause new problems, I tried to select used middlewares when `app.run()` called, but the whole middlewares need a iteration to sort by path. In my conditions, directly returned middlewares didn't cost too much CPU time, so I didn't merge any optimize code.

**Comment by SparklingFun** [comment]
Migrated to Discussions 👏
